
# Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

agent-services:
  namespace: default
  serviceAccount: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  storageClassName: ''
analytics-services:
  namespace: default
  serviceAccount: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  storageClassName: ''
cache-services:
  namespace: default
  serviceAccount: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  storageClassName: ''
etcd:
  namespace: default
  serviceAccount: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  storageClassName: ''
milvus:
  namespace: default
  serviceAccount: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  storageClassName: ''
minio:
  namespace: default
  serviceAccount: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  storageClassName: ''
pgadmin:
  namespace: default
  serviceAccount: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  storageClassName: ''
postgres:
  namespace: default
  serviceAccount: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  storageClassName: ''
retriever-canonical:
  namespace: default
  serviceAccount: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  storageClassName: ''
retriever-structured:
  namespace: default
  serviceAccount: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  storageClassName: ''
nemollm-inference:
  namespace: default
  serviceAccount: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  storageClassName: ''
nemollm-embedding:
  namespace: default
  serviceAccount: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  storageClassName: ''
ranking-ms:
  namespace: default
  serviceAccount: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  storageClassName: ''
api-gateway:
  namespace: default
  serviceAccount: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  storageClassName: ''
ingest-client:
  namespace: default
  serviceAccount: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  storageClassName: ''
